apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: Go-thu-oct-9
          artifact-id: 16dcc250-72fc-43f9-a7d4-20816c3fe756
          target-environment: ecr-qa